version: '3.9'

services:
  react-app:
    image: react-app
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
