name: Deploy to Firebase Hosting

on:
    push:
        branches:
            - main
    workflow_dispatch: # Позволяет запускать вручную

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Check Node.js version
              run: node -v

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: CI=false npm run build

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Set up Google Application Credentials
              run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcp-key.json
              shell: bash

            - name: Deploy to Firebase Hosting
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
              run: |
                  echo "Deploying to Firebase Hosting..."
                  firebase deploy --only hosting
